### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [GA114/tc359p1#1]
The app in the repo looks good, but there seems to be a problem with [the hosted version on Heroku](https://whispering-peak-7573.herokuapp.com/). You can check your Heroku logs by going to your application directory on your computer and typing `heroku logs` into the terminal. That may give you something to Google.

**Comment by GA114** [comment]
Oops — I had scaled the dyno to 0 to keep from busting my free time on Heroku.

Scaled back to 1. Give it a try now.

**Comment by chrisvfritz** [comment]
:+1: Fixed! And each app can actually safely be kept scaled to 1, since Heroku provides 750 free hours per month, per app (and the maximum hours in a month is 744 hours, so you could leave it running 24/7 and still be good). From [Heroku's Usage & Billing docs](https://devcenter.heroku.com/articles/usage-and-billing#750-free-dyno-hours-per-app):

> Heroku automatically credits each app with 750 free dyno-hours per month, which are clearly identified on your invoice.

> This allotment can be used for any type of dyno (i.e. web, worker, console), of any dyno size.

> Your free dyno-hours will allow you to run one 1X dyno for an entire month free of charge – although you may choose to run two 1X dynos for ½ of a month instead.

**Comment by GA114** [comment]
I had them both pushed to Heroku at the same time, and I assumed sleeping dynos counted towards those hours.

**Comment by chrisvfritz** [comment]
It certainly never hurts to be overly cautious. You are correct that a sleeping dyno continues to accrue usage, but each app has its own free 750 dyno-hours per month, so you can actually have many apps pushed to Heroku simultaneously, all running constantly on 1 dyno each, and still never have to pay a cent. :smile:

**Comment by GA114** [comment]
What?! Every app?! That's awesome! I thought the limit was account-wide! Good lord, my reading comprehension is in the...y'know.

**Comment by chrisvfritz** [comment]
Hey, it seems like you actually looked at the docs though - that's probably more than most people. And it *does* seem too good to be true, right? Just FYI, this works not only for Ruby apps, but also for Node.js and Python apps (since you mentioned you have JavaScript and Python experience).

With an unverified account however (meaning an account with no credit card information attached), you are limited to 5 free apps. When verified, you get up to 100 free apps.
